/*
 * Factern API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.factern.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Agent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-25T15:20:44.090-04:00")
public class Agent {
  @SerializedName("app")
  private String app = null;

  @SerializedName("representing")
  private String representing = null;

  @SerializedName("login")
  private String login = null;

  public Agent app(String app) {
    this.app = app;
    return this;
  }

   /**
   * Get app
   * @return app
  **/
  @ApiModelProperty(required = true, value = "")
  public String getApp() {
    return app;
  }

  public void setApp(String app) {
    this.app = app;
  }

  public Agent representing(String representing) {
    this.representing = representing;
    return this;
  }

   /**
   * Get representing
   * @return representing
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRepresenting() {
    return representing;
  }

  public void setRepresenting(String representing) {
    this.representing = representing;
  }

  public Agent login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Agent agent = (Agent) o;
    return Objects.equals(this.app, agent.app) &&
        Objects.equals(this.representing, agent.representing) &&
        Objects.equals(this.login, agent.login);
  }

  @Override
  public int hashCode() {
    return Objects.hash(app, representing, login);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Agent {\n");
    
    sb.append("    app: ").append(toIndentedString(app)).append("\n");
    sb.append("    representing: ").append(toIndentedString(representing)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

